In [1]:
print('Глава 2. Предобработка исследовательских данных')

Глава 2. Предобработка исследовательских данных


In [2]:
print('1. Работа с библиотекой numpy')

1. Работа с библиотекой numpy


In [13]:
print('1.1')

1.1


In [14]:
import numpy as np

a=np.array([[2.3, 5.1, 4.7],
            [3.5, 6.7, 1.5],
            [8.4, 3.1, 9.2]])

b=np.array([[4.3, 8.1, 0.1],
            [3.7, 6.2, 1.5],
            [2.4, 5.7, 4.7]])

In [15]:
string,column=a.shape
string_1,column_1=b.shape

In [16]:
print("а содержит", string, "строк и", column, "столбцов.")
print("b содержит", string_1, "строк и", column_1, "столбцов.", end="\n"*2)

а содержит 3 строк и 3 столбцов.
b содержит 3 строк и 3 столбцов.



In [17]:
print(a+b, end="\n"*2)
print(a-b, end="\n"*2)
print(a*b, end="\n"*2)
print(a/b, end="\n"*2)

[[ 6.6 13.2  4.8]
 [ 7.2 12.9  3. ]
 [10.8  8.8 13.9]]

[[-2.  -3.   4.6]
 [-0.2  0.5  0. ]
 [ 6.  -2.6  4.5]]

[[ 9.89 41.31  0.47]
 [12.95 41.54  2.25]
 [20.16 17.67 43.24]]

[[ 0.53488372  0.62962963 47.        ]
 [ 0.94594595  1.08064516  1.        ]
 [ 3.5         0.54385965  1.95744681]]



In [18]:
print(pow(a,2),end="\n"*2)
print(b/2,end="\n"*2)

[[ 5.29 26.01 22.09]
 [12.25 44.89  2.25]
 [70.56  9.61 84.64]]

[[2.15 4.05 0.05]
 [1.85 3.1  0.75]
 [1.2  2.85 2.35]]



In [19]:
cos_a=np.cos(a)
sin_b=np.sin(b)

In [20]:
print("cos a:", cos_a,end="\n"*2)
print("sin b:", sin_b,end="\n"*2)
print("cos a + sin b:")
print(cos_a+sin_b)

cos a: [[-0.66627602  0.37797774 -0.01238866]
 [-0.93645669  0.91438315  0.0707372 ]
 [-0.51928865 -0.99913515 -0.97484362]]

sin b: [[-0.91616594  0.96988981  0.09983342]
 [-0.52983614 -0.0830894   0.99749499]
 [ 0.67546318 -0.55068554 -0.99992326]]

cos a + sin b:
[[-1.58244196  1.34786755  0.08744475]
 [-1.46629283  0.83129375  1.06823219]
 [ 0.15617453 -1.54982069 -1.97476688]]


In [21]:
print('1.2')

1.2


In [23]:
aq = np.array([1.2, 2.4, 3.0, 3.5, 6.7, 1.5, 8.4, 3.1, 9.2])

In [24]:
print(a.shape,end="\n"*2)

(3, 3)



In [25]:
arr_1=a.reshape((9, 1))
print(arr_1,end="\n"*2)

[[2.3]
 [5.1]
 [4.7]
 [3.5]
 [6.7]
 [1.5]
 [8.4]
 [3.1]
 [9.2]]



In [26]:
arr_2=a.reshape((3, 3))
print(arr_2,end="\n"*2)

[[2.3 5.1 4.7]
 [3.5 6.7 1.5]
 [8.4 3.1 9.2]]



In [27]:
print(arr_2.max(axis=0),end="\n"*2)
print(arr_2.max(axis=1),end="\n"*2)

[8.4 6.7 9.2]

[5.1 6.7 9.2]



In [29]:
print(arr_2.min(axis=0),end="\n"*2)
print(arr_2.min(axis=1),end="\n"*2)

[2.3 3.1 1.5]

[2.3 1.5 3.1]



In [30]:
print(arr_2.sum(axis=0),end="\n"*2)
print(arr_2.sum(axis=1),end="\n"*2)

[14.2 14.9 15.4]

[12.1 11.7 20.7]



In [31]:
print('1.3')

1.3


In [32]:
a = np.array([[4, 2], [9, 1]])
b = np.array([[5, 3], [2, 5]])

In [35]:
new_array_1 = np.vstack((a, b))
print(new_array_1, end="\n"*2)

[[4 2]
 [9 1]
 [5 3]
 [2 5]]



In [36]:
array_2 = new_array_1[:,0][0:3]
print(array_2, end="\n"*2)

[4 9 5]



In [37]:
print(array_2.sum())
print(array_2.min())
print(array_2.max())

18
4
9


In [38]:
new_array_2 = np.hstack((a, b))
print(new_array_2)

[[4 2 5 3]
 [9 1 2 5]]


In [39]:
print(new_array_2[0,:][0:3])

[4 2 5]


In [40]:
print(sum(new_array_2[0,:][0:3]))
print(max(new_array_2[0,:][0:3]))
print(min(new_array_2[0,:][0:3]))

11
5
2


In [41]:
print('1.4')

1.4


In [46]:
from numpy import linalg as lg

a = np.array([[5, 4],[2, -6]])
b = np.array([14, -2])
decide =lg.solve(a,b)     #linalg.solve(a, b) - решает систему линейных уравнений Ax = b.
print(decide)

[2. 1.]


In [47]:
print('1.5')

1.5


In [48]:
a = np.array([[2, 8],
              [1, -6]])

b = np.array([[3, 2, 7],
             [4, 1, 8],
             [6, 3, 7]])

c = np.array([[4, 3, 2, 7],
             [6, 1, 1, -2],
             [7, 5, 8, 1],
             [9, 5, -3, -5]])

In [49]:
print(a.transpose(),end="\n"*2)
print(b.transpose(),end="\n"*2)
print(c.transpose(),end="\n"*2)

[[ 2  1]
 [ 8 -6]]

[[3 4 6]
 [2 1 3]
 [7 8 7]]

[[ 4  6  7  9]
 [ 3  1  5  5]
 [ 2  1  8 -3]
 [ 7 -2  1 -5]]



In [50]:
print(lg.inv(a),end="\n"*2)   #linalg.inv(a) - обратная матрица.
print(lg.inv(b),end="\n"*2)   #linalg.inv(a) - обратная матрица.
print(lg.inv(c),end="\n"*2)   #linalg.inv(a) - обратная матрица.

[[ 0.3   0.4 ]
 [ 0.05 -0.1 ]]

[[-0.5483871   0.22580645  0.29032258]
 [ 0.64516129 -0.67741935  0.12903226]
 [ 0.19354839  0.09677419 -0.16129032]]

[[ 0.05464191  0.23129973 -0.05251989 -0.0265252 ]
 [-0.00424403 -0.37718833  0.11087533  0.16710875]
 [-0.06153846  0.03076923  0.10769231 -0.07692308]
 [ 0.13103448  0.02068966 -0.04827586 -0.03448276]]



In [59]:
print('Определитель для а=', round(lg.det(a)),end="\n"*2)  #linalg.det(a) - определитель.
print('Определитель для b=', round(lg.det(b)),end="\n"*2)  #linalg.det(a) - определитель.
print('Определитель для c=', round(lg.det(c)), end="\n"*2)  #linalg.det(a) - определитель.

Определитель для а= -20

Определитель для b= 31

Определитель для c= 1885



In [61]:
axis0 = np.split(b, 3, axis=0) #split сканирует всю строку и разделяет ее в случае нахождения разделителя.
print('норма вектора для axis0 =', round(lg.norm(axis0)),end="\n"*2)  #linalg.norm(x[, ord, axis]) - норма вектора или оператора.

норма вектора для axis0 = 15



In [60]:
axis1 = np.split(c, 4, axis=1)
print('норма вектора для axis1 =', round(lg.norm(axis1)),end="\n"*2)

норма вектора для axis1 = 20



In [62]:
import random

a = np.array([random.randint(0, 100) for i in range(0, 100, 1)])
print(a)

count = 0
for i in a:
     if i>50:
        count+=1
print (count)

count_new = 0
count_new = sum(map(lambda item: item > 50, a))
print(count_new)

[ 72  66  53  17  63  17  22  65  64  49   3   7  74   8   7  64  83  93
  64   0  13  24  63   5  55  35   7  13  17  68  59  91  30  70  47  59
 100  28   2  86  77  51   3   8  67   1   0  86  80  25  63  78  77  47
  80  81  89  88  91   9  91  41   8  54  66  41  76  20   7  94  69  59
  52  83 100 100  70  10  37   2   2  81  94  69   8  72  69   6  90  76
  29  78  72  15  28  60  60  33  53  50]
57
57
